<?php if (isset($name)) : ?>
	<h2> <?= htmlspecialchars($name); ?>!</h2>
<?php else: ?>
	<p></p>
<?php endif; ?>





<div class="container">
  <div class="row">
    <div class="col-sm">
    <div><img alt="" src="/public/img/building_1.png">
      <p>12</p>
      </div>
      
    </div>
    <div class="col-sm">
      <img alt="" src="/public/img/building_1.png">
    </div>
    <div class="col-sm">
      <img alt="" src="/public/img/building_1.png">
    </div>
  </div>
</div>

